import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { byWord } from "./entry-index.js";
import {
  categoryMessages,
  entries,
  lookupKey,
  type BadWordCategory,
  type BadWordEntry,
} from "../src/rules/no-bad-words.js";

const headings: Record<BadWordCategory, string> = {
  ai: "AI writing",
  cliche: "Clichés",
  empty: "Empty phrases",
  "explained-verb": "Explained verbs",
  formalism: "Formalisms",
  hedge: "Hedges",
  opinion: "Personal opinion phrases",
  redundancy: "Redundancies",
  variation: "Inelegant variations",
};

const blurbs: Record<BadWordCategory, string> = {
  ai: "Words and expressions that turn up constantly in text generated by language models. None of them is wrong on its own; together they are a house style, and readers have learned to recognize it.",
  cliche:
    "Overused expressions that most readers have already seen a hundred times before. They add nothing new, don't engage readers and make your content look generic.",
  empty:
    "Phrases that add no meaning to your text. Removing them costs you nothing and adds focus and clarity.",
  "explained-verb":
    'A verb plus a modifier where one stronger verb already exists. "Walk slowly" is "crawl"; "become smaller" is "shrink".',
  formalism:
    "Academic and institutional constructions. They are not errors, but they set a distant, official tone, which is usually not what you want.",
  hedge:
    "Expressing doubt about your confidence in your own statements. This is expected in academic writing and undermines you almost everywhere else.",
  opinion:
    "Constructions that signal something is the author's opinion. Context usually establishes that already, so these are often just noise.",
  redundancy:
    'Phrases and word choices that say the same thing twice. An "added bonus" is a bonus; an "actual fact" is a fact.',
  variation:
    "Rare words and long expressions standing in for common short ones, often chosen to avoid repeating a word. Sometimes this produces better prose. Usually it does not.",
};

const order: BadWordCategory[] = [
  "empty",
  "redundancy",
  "variation",
  "explained-verb",
  "hedge",
  "opinion",
  "formalism",
  "cliche",
  "ai",
];

const escape = (text: string) => text.replace(/\|/gu, "\\|");

const fix = ({ suggestions, message, category }: BadWordEntry) => {
  if (suggestions && suggestions.every((suggestion) => suggestion === "")) {
    return "_delete_";
  }

  if (suggestions) {
    return suggestions.map((suggestion) => `\`${suggestion}\``).join(", ");
  }

  return escape(message ?? categoryMessages[category]);
};

const table = (rows: BadWordEntry[]) =>
  [
    "| Expression | Replace with |",
    "| --- | --- |",
    ...rows.map((entry) => `| ${escape(entry.phrase)} | ${fix(entry)} |`),
  ].join("\n");

const byCategory = order
  .map((category) => {
    const rows = entries.filter((entry) => entry.category === category);
    return [
      `### ${headings[category]} (${rows.length})`,
      "",
      blurbs[category],
      "",
      `Default message: _${categoryMessages[category]}_`,
      "",
      table(rows),
    ].join("\n");
  })
  .join("\n\n");

const alphabetical = [...entries].sort((a, b) =>
  lookupKey(a.phrase).localeCompare(lookupKey(b.phrase), "en"),
);

const words = [...byWord]
  .sort(([a], [b]) => a.localeCompare(b, "en"))
  .map(
    ([word, found]) =>
      `**${escape(word)}** — ${found
        .map(({ phrase }) => escape(phrase))
        .join("; ")}`,
  )
  .join("  \n");

const document = `<!--
  Generated by \`npm run build-docs\` from src/rules/no-bad-words.ts.
  Do not edit this file directly; edit the entries and regenerate.
-->

# No Bad Words

Every word and expression enlint flags on sight.

- [Every expression, alphabetically](#every-expression-alphabetically)
- [By word](#by-word)
- [By category](#by-category)

## Every expression, alphabetically

Sorted ignoring a leading "a", "an" or "the", so "a beacon of" files under B.

| Expression | Category | Replace with |
| --- | --- | --- |
${alphabetical
  .map(
    (entry) =>
      `| ${escape(entry.phrase)} | ${headings[entry.category]} | ${fix(entry)} |`,
  )
  .join("\n")}

## By word

Every word a rule turns on, and the rules that turn on it. The alphabetical
table above files each expression under one phrase, but a rule usually names
several words, and any of them might be the one you are checking: "profound
implication" and "broad implication" are far apart above and next to each other
here.

Use this before adding an expression. \`npm run lookup <word>\` asks the same
question from the command line and also reports which rules sit underneath
broader ones.

${words}

## By category

${byCategory}
`;

await writeFile(
  fileURLToPath(new URL("../docs/no-bad-words.md", import.meta.url)),
  document,
);
console.log(`docs/no-bad-words.md: ${entries.length} expressions`);
